### ISSUE TITLE
Please add the documentation URL in the repo's About section

### ISSUE THREAD

**Issue by kishannareshpal** [danielrbradley/array-fns#28]
### Request:
Hi, could you please add the lib's documentation link in the repository's About section?
- https://www.danielbradley.net/array-fns/

<img width="1301" alt="Screenshot 2023-06-30 at 17 18 16" src="https://github.com/danielrbradley/array-fns/assets/25407841/f05e4640-bf51-4c8d-838e-c483f6f350d8">

### Why?
Its really easy to miss the [![TypeDoc docs](https://img.shields.io/badge/TypeDoc-docs-lightgrey.svg)](https://www.danielbradley.net/array-fns/) in the README.

Thanks for this nice library!

**Comment by danielrbradley** [comment]
Done!
